function [Wout,Hout] = mergeSources_2 (W,H,X, sel2D)
%Merge sources generated by NNMF2
%W: Spatial footprints, [# selected pixels x # sources]
%H: Time trces [# sources x # timepoints]
%X: The data being factorized, [#selected pixels x #timepoints]
%sel2D: a logical array indicaing the spatial location of selected pixels,
%must have exactly [#selected pixels] TRUE values 

sz = [size(sel2D,1) size(sel2D,2)];

%sort by variance; nnmf usually does htis automatically but we disabled it
%in nnmf2
[~, sortorder] = sort(sum(W.^2,1), 'descend');
W = W(:,sortorder);
H = H(sortorder,:);

resid = X-W*H;
k = size(W,2); %number of sources

%discard low SNR sources
%compare variance explained to residual variance
SNR = nan(1,k);
for sourceIx = k:-1:1
    selPx = W(:,sourceIx)>0;
    %D = resid(selPx, :);
    vD1 = sum((sum(W(selPx,sourceIx),1).*H(sourceIx,:)).^2);
    vResid = sum(sum(resid(selPx,:),1).^2,2);
    SNR(sourceIx) = vD1./vResid;
end
SNRcut = 1;
is_gui_mode = usejava('desktop') && usejava('awt');
if ~any(SNR>SNRcut) && is_gui_mode
    figure('name', 'This recording yielded no sources above SNR cutoff'),
    imagesc(X);
    error('No ROIs met the SNR cutoff, aborting!')
end
W = W(:,SNR>SNRcut);
H = H(SNR>SNRcut,:);
resid = X-W*H;
k = size(W,2); %number of sources

if k == 0
    Wout = W;
    Hout = H;
    return
end

%convert W to Wfull and dilate to compute overlap
Wfull = zeros(sz(1)*sz(2), k);
Wfull(sel2D,:) = W;
Wfull = reshape(Wfull, [sz k]);
S = strel([0 1 0; 1 1 1; 0 1 0]); %strel([0 1 0 ; 1 1 1 ; 0 1 0]);
Wd = reshape(imdilate((Wfull>0), S),[], k);
overlap = (Wd(sel2D,:)'*(W>0))>2;
keep = true(1,k);
merged = false(1,k); 

crit1 = nan(k,k);
%crit2 = nan(k,k);

%for every pair of overlapping or adjacent sources
for sourceIx1 = 1:k-1
    for sourceIx2 = sourceIx1+1:k
        %ensure there is overlap
        if ~overlap(sourceIx1, sourceIx2) || ~all(keep([sourceIx1 sourceIx2]))
            continue
        end

        %compute D, the data at the pixels supported by the sources,
        %unexplained by others
        selPx = W(:,sourceIx1)>0 |  W(:,sourceIx2)>0;
        D = resid(selPx, :) + (W(selPx,sourceIx1)*H(sourceIx1,:)) + (W(selPx,sourceIx2)*H(sourceIx2,:));

        %perform a new NMF on this data with one source
        W1 = sum(W(selPx,[sourceIx1 sourceIx2]),2);
        for iter = 1:10
            H1 = max(0, W1\D); H1 = H1./sum(H1.^2);
            W1 = max(0, D/H1);
        end

        % %visualize W1
        % W1sel = nan(numel(selPx),1);  W1sel(selPx) = W1;
        % W1full = nan(numel(sel2D),1); W1full(sel2D(:)) = W1sel;
        % W1full = reshape(W1full, size(sel2D));

        %compute AIC
        sigma = std(resid(selPx, :),1,2);

        resid_1source=  D-W1*H1;
        logL_1source = sum(log(normpdf(resid_1source./sigma)), 'all');%sum(log(1/(sigma.*sqrt(2*pi))) -(((resid_1source./sigma).^2)/2), 1) %gaussian log likelihood
        logL_2sources = sum(log(normpdf(resid(selPx,:)./sigma)), 'all');
        k_1source = sum(W1(:)>0) + numel(H1);
        k_2sources = sum(W(:, [sourceIx1 sourceIx2])>0, 'all') + 2*numel(H1);
        AIC1 = 2.*k_1source - 2*logL_1source;
        AIC2 = 2.*k_2sources - 2*logL_2sources;
        
        crit1(sourceIx1,sourceIx2) = AIC2-AIC1;
        if AIC1<AIC2 %use the 1-source model
            keep(sourceIx2) = false;
            merged(sourceIx1) = true;
            W(selPx,sourceIx1) = W1;
            H(sourceIx1,:) = H1;
            W(:, sourceIx2) = 0;
            H(sourceIx2,:) = 0;
            resid(selPx, :) = resid_1source;
        end

        %compute the variance explained by the model with one source or both
        % v2m1 = sum((W1*H1).^2, 'all').^2;
        % v2m2 = sum((W(selPx,sourceIx1)*H(sourceIx1,:)).^2, 'all').^2 + sum((W(selPx,sourceIx2)*H(sourceIx2,:)).^2, 'all').^2;
        % crit2(sourceIx1,sourceIx2) = v2m1./v2m2;
    end
end
Wout = W(:,keep);
Hout = H(keep,:);
end