classdef spineAnalysisExpt < handle
    %like spineanalysis, but reads data directly from .dat files
    properties
        hFigPanel1; %image panel
        hFigPanel2; %image panel
        hButtonPanel; %button panel
        hF; %figure handle
        hGrid;
        hAx; %axes handle
        hButton1; hButton1c;
        hButton2;
        hButton3;
        hButton4;
        hButtonCh;
        hEditCh;

        hROIs;
        hIm; %image object

        chDim = 3; %images are in XYCT order
        timeDim = 4; %images are in XYCT order
        showChannel = 1;

        %butterworth filter parameters for highpass
        b2;
        a2;

        analyzeHz = 100; %framerate at which to analyze

        exptSummary; %summary file generated by summarizeMultiRoi
        selDMD; %which DMD to display
        IM;
        IMc; %correlation image; normalized to median 0 standard deviation 1
        IMsk; %skewness image; normalized to median 0 standard deviation 1
        IMact; %the image used to display activity
        IMavg; %average image, normalized to [0 1]
        
        numChannels;
        fn;
        dr = [];
        drsave;
        fnsave;

        defaultChLabels = {'iGluSnFr'; 'jRGECO'};
        Clevel = 3; %adjustable threshold for display of correlation image, in standard deviations
    end

    methods
        function obj = spineAnalysisExpt(fn, selDMD)
            if nargin<1 || isempty(fn)
                [obj.fn, obj.dr] = uigetfile('*.mat', 'Select a summary file');
            else
                obj.selDMD = selDMD;
            end

            %load summary data
            load([obj.dr filesep obj.fn], 'exptSummary');
            obj.exptSummary = exptSummary;

            if nargin<2 || isempty(selDMD)
                obj.selDMD = str2double(questdlg('Select a DMD', 'spine analysis', '1', '2', '1'));
            else
                obj.selDMD = selDMD;
            end

            %structural image
            IMavg = obj.exptSummary.meanIM{obj.selDMD};
            IMavg = IMavg-min(IMavg,[], [1 2], 'omitnan');
            obj.IMavg = sqrt(IMavg./max(IMavg, [],[1 2]));

            obj.IMact = obj.exptSummary.actIM{obj.selDMD};
            obj.numChannels = size(obj.IMavg,3);

            %gui creation
            obj.hF = uifigure('name', ['Spine analysis - ' obj.fn], 'KeyPressFcn', @obj.kpf);
            obj.hGrid = uigridlayout(obj.hF);
            obj.hGrid.RowHeight = {50, '1x'};
            obj.hGrid.ColumnWidth = {'1x'};

            obj.hButtonPanel = uigridlayout(obj.hGrid);
            obj.hButtonPanel.RowHeight = {'1x'};
            obj.hButtonPanel.ColumnWidth = {100,100,100,100,100,100, 100,100,100};
            obj.hButton1 = uibutton(obj.hButtonPanel, 'Text', 'Draw Polygon', 'ButtonPushedFcn', @obj.drawPolygon);
            obj.hButton1c = uibutton(obj.hButtonPanel, 'Text', 'Draw Circle', 'ButtonPushedFcn', @obj.drawCircle);
            obj.hButton2 = uibutton(obj.hButtonPanel, 'Text', 'Save ROIs', 'ButtonPushedFcn', @obj.saveROIs);
            obj.hButton3 = uibutton(obj.hButtonPanel, 'Text', 'Load ROIs', 'ButtonPushedFcn', @obj.loadROIs);
            obj.hButton4 = uibutton(obj.hButtonPanel, 'Text', 'Analyze', 'ButtonPushedFcn', @obj.analyze);
            for chIx = 1:obj.numChannels
                obj.hButtonCh(chIx) = uibutton(obj.hButtonPanel, 'Text', ['Show Ch' num2str(chIx) ':'], 'ButtonPushedFcn', @(x1,x2)(obj.setCh(chIx)));
                obj.hEditCh(chIx) = uieditfield(obj.hButtonPanel, 'Value', obj.defaultChLabels{chIx});
            end

            obj.hAx = uiaxes(obj.hGrid);
            obj.hIm = imshow(cat(3, obj.IMact(:,:,obj.showChannel)./obj.Clevel, obj.IMavg(:,:,obj.showChannel), obj.IMavg(:,:,obj.showChannel)),'parent', obj.hAx);
            set(obj.hIm, 'HitTest', 'off', 'pickableparts', 'none', 'clipping', 'on')
            set(obj.hAx, 'hittest', 'off', 'PickableParts', 'all')
        end

        function setCh(obj,chIx)
            obj.showChannel = chIx;
            updateDisplay(obj);
        end

        function updateDisplay(obj)
            set(obj.hIm, 'CData',cat(3, obj.IMact(:,:,obj.showChannel)./obj.Clevel, obj.IMavg(:,:,obj.showChannel), obj.IMavg(:,:,obj.showChannel)))
        end

        function maskData = roiMasks(obj)
            %generate masks for the ROIs
            tix = 0;
            maskData.names ={}; %INITIALIZE
            for rix = 1:length(obj.hROIs)
                try
                    roiObj = findobj(obj.hROIs(rix));
                catch
                    continue
                end
                tix = tix+1; %tix will count the total # of valid ROIs
                name = roiObj.Label;
                assert(~isempty(name), 'ROI names cannot be empty!');
                assert(~any(strcmpi(maskData.names, name)), 'A ROI name was duplicated!')
                maskData.names{tix} = name;

                maskData.mask{tix} = roiObj.createMask;
                [rr,cc] = find(maskData.mask{tix});
                maskData.bbox{tix} = [min(cc) min(rr) ; max(cc) max(rr)];
                maskData.mask{tix} = maskData.mask{tix}(maskData.bbox{tix}(1,2):maskData.bbox{tix}(2,2), maskData.bbox{tix}(1,1):maskData.bbox{tix}(2,1));
            end
            maskData.nROIs = tix;
        end

        function sData = analyze(obj, ~, ~)
            [fnsave, drsave] = uiputfile([obj.dr filesep obj.fn(1:end-4) '_DMD' int2str(obj.selDMD) 'analyzed.mat']);

            maskData = obj.roiMasks;

            %for each valid trial, load the fast data
            validTrials = find(obj.exptSummary.validTrials);
            sData.traces = nan(1,1,1,1,1); %time, roi, channel, traceType, trial
            sData.noise = nan(1,1,1,1); %roi, trial, channel, traceType
            sData.motionC = nan(1,1); %time, roi, channel, traceType, trial
            sData.motionR = nan(1,1); %time, roi, channel, traceType, trial
            sData.alignError = nan(1,1); %time, roi, channel, traceType, trial
            
            for trialIx = 1:length(validTrials) %TMP
                fnTrial = obj.exptSummary.fns{validTrials(trialIx)};
                dmdNumStringIndex = strfind(fnTrial, 'DMD1')+3;
                fnTrial(dmdNumStringIndex) = int2str(obj.selDMD);
                
                ind =strfind(fnTrial, '_REGISTERED');
                datFn = [fnTrial(1:ind-1) '.dat'];

                sData.fns{trialIx} = datFn;

                if ~exist([obj.exptSummary.dr filesep datFn], 'file')
                    msgbox(['Dat File: ' datFn ' not found. Please select location...']);
                    [~, obj.exptSummary.dr] = uigetfile([obj.dr filesep '*.dat']); %update directory
                end

                if trialIx==1
                    meta = loadMetadata([obj.exptSummary.dr datFn]);
                    linerateHz = 1/meta.linePeriod_s;
                    dt = ceil(linerateHz/obj.analyzeHz);
                end

                %load metadata
                S2data = slap2.Slap2DataFile([obj.exptSummary.dr datFn]);
                numLines = S2data.totalNumLines;
                numFrames = floor(numLines/dt);
                frameIxs = dt*(1:numFrames);

                %load alignment data
                aData = loadAlignmentData([obj.exptSummary.dr datFn]);
                motionC = interp1(aData.DSframes,aData.motionDSc, frameIxs, 'linear', 'extrap');
                motionR = interp1(aData.DSframes,aData.motionDSr, frameIxs, 'linear', 'extrap');
                aError =  interp1(aData.DSframes,aData.aError, frameIxs, 'linear', 'extrap');
                motPreds = [motionC ; motionR ; motionC.^2 ; motionR.^2 ; motionC.^3 ; motionR.^3 ; motionC.*motionR ; ones(size(motionC))];

                %load the high time resolution data
                %extize
                for rix =maskData.nROIs:-1:1
                    D{rix} = nan([maskData.bbox{rix}(2,2)-maskData.bbox{rix}(1,2)+1, maskData.bbox{rix}(2,1)-maskData.bbox{rix}(1,1)+1, obj.numChannels, numFrames]);
                end

                disp('Reading High-res data')
                for fix = 1:numFrames
                    if mod(fix, 100)==1
                        disp(['Frame ' int2str(fix) ' of ' int2str(numFrames) '...'])
                    end
                    for cix = 1:obj.numChannels
                        fdata = S2data.getImage(cix, ceil(fix*dt), 2*dt, 1); %Channel, Frame, Timewindow, Zindex
                        for rix = 1:maskData.nROIs
                            %query rows
                            Rq = obj.exptSummary.perTrialAlignmentOffsets(1,validTrials(trialIx), obj.selDMD) + aData.cropRow+motionR(fix)-1+(maskData.bbox{rix}(1,2):maskData.bbox{rix}(2,2));
                            %query columns
                            Cq = obj.exptSummary.perTrialAlignmentOffsets(2,validTrials(trialIx), obj.selDMD) + aData.cropCol+motionC(fix)-1+(maskData.bbox{rix}(1,1):maskData.bbox{rix}(2,1));
                            %meshgrid uses X,Y convention not R,C
                            [Cq,Rq] = meshgrid(Cq,Rq);
                            D{rix}(:,:,cix,fix) = interp2(fdata,Cq,Rq);
                        end
                    end
                end

                [traces, noise] = obj.extractTraces(D, maskData, motPreds); %
                
                %traces dimensions: [time, roi, channel, traceType]
                sData.trialLength(trialIx) = size(traces,1);
                if size(traces,1)>size(sData.traces,1) %The first dimension needs to be extended with nans
                    sData.traces(end+1:size(traces,1),:,:,:,:) = nan;
                    sData.motionC(end+1:size(traces,1),:) = nan;
                    sData.motionR(end+1:size(traces,1),:) = nan;
                    sData.alignError(end+1:size(traces,1),:) = nan;
                end
                sData.traces(:,:,:,:,trialIx) = nan; %prefill with nans
                sData.motionC(:,trialIx) = nan;
                sData.motionR(:,trialIx) = nan;
                sData.alignError(:,trialIx) = nan;

                %accumulate per-trace data
                sData.traces(1:size(traces,1),1:length(D),1:obj.numChannels, 1:size(traces,4), trialIx) = traces; %time, roi, channel, traceType, trial
                sData.noise(1:length(D), 1:obj.numChannels, 1:size(traces,4), trialIx) = noise; %roi, channel, traceType, trial
                sData.motionC(1:length(motionC),trialIx) =  motionC;
                sData.motionR(1:length(motionC),trialIx) =  motionR;
                sData.alignError(1:length(motionC),trialIx) = aError;

            end
            sData.maskData = maskData;
            sData.frametime = 1/obj.analyzeHz;
            save([drsave filesep fnsave], 'sData')
    
            %save figure
            disp('saving figure')
            exportgraphics(obj.hAx, [drsave filesep fnsave(1:end-4) '_RoisFigure.pdf'], 'ContentType', 'vector');
        end

        function [traces, noise] = extractTraces(obj, D, maskData, motPreds)
            nROIs = maskData.nROIs;
            numFrames = size(D{1},4);
            %extracts traces for a given trial
            traces = nan(numFrames, nROIs, obj.numChannels, 2);
            noise = nan(nROIs, obj.numChannels,2);
            for rix = 1:nROIs
                Dsz = size(D{rix});
                for cix = 1:obj.numChannels
                    DD = double(reshape(D{rix}(:,:,cix,:), [], Dsz(4)));
                    nans = isnan(DD);
                    numVal = sum(~nans, 2);
                    [~,p] = sort(numVal,'descend');
                    r = (1:length(p))'; r(p) = r;

                    %select pixels and frames to include
                    selpix = (numVal./max(numVal))>(r./max(r) + 0.05);
                    selframes = ~any(nans(selpix,:),1);
                    selpix = ~any(nans(:,selframes),2);
                    DD = DD(selpix,selframes); %discard nans
                    if isempty(DD) || sum(selframes)<100 || sum(selpix)<4
                        continue
                    end

                    trace0= sum(DD(maskData.mask{rix}(selpix),:),1); %trace0 is the SUM over all selected pixels

                    %remove motion noise in the singular components of the movie
                    mDD = mean(DD,2);
                    [U,S,V] = svds(DD-mDD, floor(sum(selpix)/10));
                    Vcorr = V;
                    for vix = 1:size(V,2)
                        [~, Vcorr(:, vix)] = obj.decorrelateMotion(V(:,vix), motPreds(:,selframes));
                    end
                    DDcorr = DD-(U*S*Vcorr'); %motion-corrected data: the original data minus the reconstructed motion artefact
                    trace1= sum(DDcorr(maskData.mask{rix}(selpix), :),1); % the decorrelated trace computed from the mask alone

                    %compile output
                    traces(selframes, rix,cix,1) = trace0; %raw ROI, without decorrelating motion variables
                    noise(rix,cix,1) = estimatenoise(trace0(1:4:end)); %noise for trace0; computed from every 4th sample because of smoothing in .dat signal extraction
                    traces(selframes, rix,cix,2) = trace1; %raw ROI, with motion variables decorrelated
                    noise(rix,cix,2) = estimatenoise(trace1(1:4:end)); %noise for trace1; computed from every 4th sample because of smoothing in .dat signal extraction
                end
            end
        end

        function saveAsH5(obj, fname, sData)
            if exist(fname, 'file')
                resp = questdlg(['The file ' fname ' already exists. Overwrite?'], 'Overwrite?', 'Yes', 'No', 'No');
                switch resp
                    case 'Yes'
                        delete(fname);
                    case 'No'
                        return
                end
            end
            nROIs = length(sData.names);

            szTrace = [size(sData.trace0,1) obj.numChannels]; %size of each trace

            %saves spine analyses data in H5 format for easier python analysis
            for roiIx = 1:nROIs
                roiName = sData.names{roiIx};

                %create data
                h5create(fname,['/fluo/raw/' roiName], [szTrace(2) szTrace(1)], 'Datatype', 'single', 'ChunkSize', min([szTrace(2) szTrace(1)], [1 2000]), 'Deflate', 5); % fluorescence from this ROI

                % write data
                h5write(fname,['/fluo/raw/' roiName],permute(sData.trace0(:,roiIx,:), [3 1 2]));

                %write attributes
                h5writeatt(fname,['/fluo/raw/' roiName],'fs', 1/aData.frametime); %sampling frequency
                h5writeatt(fname,['/fluo/raw/' roiName],'noise', sData.n0(roiIx,:)); %estimated noise, per channel
                chans = {};
                for chIx = 1:obj.numChannels
                    chans = cat(1, chans, {get(obj.hEditCh(chIx), 'Value')});
                end
                h5writeatt(fname,['/fluo/raw/' roiName],'chans', chans); %channel names
                h5writeatt(fname,['/fluo/raw/' roiName],'nPix', sum(sData.mask{roiIx}(:))); %channel names
            end

            %save global information
            h5create(fname,"/fluo/motionC",size(motionC), 'Datatype', 'single','ChunkSize', size(motionC), 'Deflate', 5); % XY movement
            h5write(fname,"/fluo/motionC",motionC);
            h5create(fname,"/fluo/motionR",size(motionR), 'Datatype', 'single','ChunkSize', size(motionR), 'Deflate', 5); % XY movement
            h5write(fname,"/fluo/motionC",motionR);
            h5create(fname,"/fluo/alignmentError",size(aData.aError), 'Datatype', 'single','ChunkSize', size(aData.aError), 'Deflate', 5); % XY movement
            h5write(fname,"/fluo/alignmentError",aData.aError);

            h5writeatt(fname,"/fluo/motionR",'fs', obj.analyzeHz);
            h5writeatt(fname,"/fluo/motionC",'fs', obj.analyzeHz);
            h5writeatt(fname,"/fluo/alignmentError",'fs', obj.analyzeHz);

        end

        function saveROIs (obj, arg1, arg2)
            if isempty(obj.drsave)
                obj.drsave = obj.dr;
            end
            [obj.fnsave, obj.drsave] = uiputfile([obj.drsave filesep obj.fn(1:end-4) '_DMD' num2str(obj.selDMD) '_ROIs.mat']);
            if isempty(obj.fnsave) || ~any(obj.fnsave)
                return
            end
            roiData = {};
            for rix = 1:length(obj.hROIs)
                try
                    S = rmfield(get(obj.hROIs(rix)), {'Parent', 'Children', 'ContextMenu'});
                    roiData = [roiData {S}];
                catch
                    %this object didn't exist
                end
            end
            save([obj.drsave filesep obj.fnsave], 'roiData');
        end

        function [corrected, traceMot] = decorrelateMotion(obj, trace, motPreds)
            %highpass filter trace
            trace = trace(:) - smooth(trace, ceil(3*obj.analyzeHz), 'lowess');
            beta = mvregress(motPreds',trace);
            traceMot = motPreds'*beta;
            corrected = trace' - traceMot';
        end

        function loadROIs (obj, arg1, arg2)
            if ~(any(obj.drsave)) || isempty(obj.drsave)
                obj.drsave = obj.dr;
            end
            [fn dr] = uigetfile([obj.drsave filesep '*_ROIS.mat']);
            load([dr filesep fn], 'roiData');

            try
                delete(obj.hROIs);
            catch
            end
            obj.hROIs = [];
            for rix = 1:length(roiData)
                switch roiData{rix}.Type
                    case 'images.roi.ellipse'
                        obj.hROIs(rix) = images.roi.Ellipse(obj.hAx, 'AspectRatio', roiData{rix}.AspectRatio, 'FixedAspectRatio', roiData{rix}.FixedAspectRatio, 'Center', roiData{rix}.Center, 'SemiAxes', roiData{rix}.SemiAxes, 'RotationAngle', roiData{rix}.RotationAngle, 'Label', roiData{rix}.Label);
                    case 'images.roi.circle'
                        obj.hROIs(rix) = images.roi.Circle(obj.hAx,'Center', roiData{rix}.Center, 'Label', roiData{rix}.Label);
                    case 'images.roi.polygon'
                        obj.hROIs(rix) = images.roi.Polygon(obj.hAx,'Position', roiData{rix}.Position, 'Label', roiData{rix}.Label);
                    otherwise
                        error('bad ROI data type');
                end

                fnms = fieldnames(roiData{rix});
                for ix =1:length(fnms)
                    try
                        set(obj.hROIs(rix), fnms{ix}, roiData{rix}.(fnms{ix}));
                    catch
                    end
                end


                cm = get(obj.hROIs(rix), 'ContextMenu');
                uimenu(cm,'Text','Set Label','MenuSelectedFcn',@(arg1,arg2)(obj.setLabel(obj.hROIs(rix)))); %add a 'Set Label' context menu
            end
        end

        function drawPolygon(obj, arg1, arg2)
            L = length(obj.hROIs)+1;
            obj.hROIs(L) = drawpolygon(obj.hAx);
            set(obj.hROIs(L), 'FaceAlpha', 0, 'labelAlpha', 0 , 'labelTextColor', 'y', 'linewidth', 0.5, 'MarkerSize', 1);
            cm = get(obj.hROIs(L), 'ContextMenu');
            uimenu(cm,'Text','Set Label','MenuSelectedFcn',@(arg1,arg2)(obj.setLabel(obj.hROIs(L)))); %add a 'Set Label' context menu
            obj.setLabel(obj.hROIs(L));
        end

        function drawCircle(obj, arg1, arg2)
            L = length(obj.hROIs)+1;
            obj.hROIs(L) = drawellipse(obj.hAx);
            set(obj.hROIs(L), 'FaceAlpha', 0, 'labelAlpha', 0 , 'labelTextColor', 'y', 'linewidth', 0.5, 'MarkerSize', 1);
            cm = get(obj.hROIs(L), 'ContextMenu');
            uimenu(cm,'Text','Set Label','MenuSelectedFcn',@(arg1,arg2)(obj.setLabel(obj.hROIs(L)))); %add a 'Set Label' context menu
            obj.setLabel(obj.hROIs(L));
        end

        function setLabel(obj, hROI)
            label = inputdlg('Set a label');
            set(hROI, 'Label', label{1});
        end
        function kpf(obj, arg1, arg2)
            switch arg2.Key
                case 'a'
                    @obj.drawPolygon;
                case 'c'
                    @obj.drawCircle;
                case 'period'
                    obj.Clevel = obj.Clevel/1.5;
                    obj.updateDisplay
                case 'comma'
                    obj.Clevel = obj.Clevel.*1.5;
                    obj.updateDisplay;
            end
        end
    end
end