function [pData, hF] = plotBCIexpt(sData, pData)
%sData is an array of structs #epochs x #DMDs in size
%each struct in sData is generated by the function spineAnalysisExpt
%
%sData.traces is an array of size [time ROIs channels traceType trial#] aligned to
%trial start. Traces have units of (photons x 100)
%
%outputs:
%figures are the figure handles
%pData is the data used in the plots

traceType = 2; ;%which trace version to use; 1=raw ROIs, 2=motion subtracted ROIs,...

%sanity check that all sData have same frametime
assert(all([sData.frametime]==sData(1).frametime));

if nargin<2 %generate pData
    [fn, dr] = uiputfile('plottingData.mat');
    %merge data from the two DMDs and compute F0
    for epoch = 1:size(sData, 1)
        pData(epoch) = mergeDMDs(sData(epoch,:));
    end
    for epoch = 1:size(sData, 1)
        pData(epoch).colors = [0.5 0.8 0; 0.8 0 0.5]; %ch1 yellow ch2 red
        pData(epoch).frametime = sData(epoch,1).frametime; %
        pData(epoch).traceType(:) = traceType;  %default trace Type for plotting
    end
    save([dr filesep fn], 'pData');
end

%make plots specific for this epoch
hF3 = plotTrialAverages(sData, pData);
hF1 = plotTotalInput(sData,pData);
hF2 = plotAllTraces(sData, pData);






end

function pData = mergeDMDs(sData)
for dmdNum = 1:length(sData)
    Tt = sData(dmdNum).traces;
    Nn = sData(dmdNum).noise;
    if dmdNum==1 %first DMD
        F = Tt;
        noise = Nn;
        dmdIxs = ones(1,size(Tt,2));
        names = sData(dmdNum).maskData.names;
    else
        if size(Tt,1)>size(F,1)
            F((size(F,1)+1):size(Tt,1),:,:,:,:) = nan;
        else
            Tt((size(Tt,1)+1):size(F,1),:,:,:,:) = nan;
        end
        F= cat(2,F,Tt);
        noise = cat(1, noise, Nn);
        dmdIxs = cat(2, dmdIxs, dmdNum*ones(1,size(Tt,2)));
        names = cat(2, names,  sData(dmdNum).maskData.names);
    end
end

pData.tau(1) = 0.02/sData(1).frametime;%Glutamate time constant in samples
pData.tau(2) = 0.05/sData(1).frametime; %Calcium time constant in samples
pData.denoiseWindow = [0.5/sData(1).frametime 0.5/sData(1).frametime];
pData.hullWindow = [0.8/sData(1).frametime 0.8/sData(1).frametime];

disp('Computing F0...')
F0 = nan(size(F));
for Ch = 1:2
    F0(:,:,Ch,:,:) = computeF0(F(:,:,Ch,:,:), pData.denoiseWindow(Ch), pData.hullWindow(Ch)); %allow F0 fitting to differ for different channels
end
dF = F-F0;
dFF = (F-F0)./max(0,F0);

pData.F=F;
pData.dF=dF;
pData.dFF = dFF;
pData.F0 = F0;
pData.noise=noise;
pData.dmdIxs= dmdIxs;
pData.names = names;
end



function hF = plotAllTraces(sData, pData)

%Figure with 2 subplots: 1 for soma, 1 for all synapses
toPlot = 'dF';
D = pData.(toPlot); %data to plot
D = D(:,:,:,pData.traceType,:);
Dnorm = D./shiftdim(sqrt(pData.noise(:,:,pData.traceType,:)), -1); %normalized to noise estimate

%get trial lengths
keepFrames = true(1, size(D,1)*size(D,5));
for trialIx = size(D,5):-1:1
    trialLength(trialIx) = find(~all(isnan(Dnorm(:,:,1,1,trialIx)),2), 1, 'last');
    keepFrames(((trialIx-1)*size(D,1)+trialLength(trialIx)+1):(trialIx*size(D,1))) = false;
end

hF = figure('name', 'all trials');
isSoma = strcmpi(pData.names, 'soma');
somaCh = 2; spineCh = 1;
hAxSoma = [];
if any(isSoma)
    hAxSoma = subplot(10,1,1);
    tmp = Dnorm(:,isSoma, somaCh,1,:);
    tmp = reshape(permute(tmp, [2 1 5 4 3]), size(tmp,2), []); %tmp is now 2D [ROIs allTime]
    tmp = tmp + 10*(0:(size(tmp,1)-1)); %offset for plotting
    tmp(:, ~keepFrames) = []; %remove ends of trials
    T = sData(1).frametime*(1:size(tmp,2));
    plot(T, tmp, 'color', pData.colors(somaCh,:));
    set(hAxSoma, 'xtick', [])
    ylabel('Z-score')
end
hAxSpines = subplot(10,1,2:10);
if any(~isSoma)
    tmp = Dnorm(:,~isSoma, spineCh,1,:);
    tmp = reshape(permute(tmp, [2 1 5 4 3]), size(tmp,2), []); %tmp is now 2D [ROIs allTime]
    tmp = tmp + 10*(0:(size(tmp,1)-1))'; %offset for plotting
    tmp(:, ~keepFrames) = []; %remove ends of trials
    T = sData(1).frametime*(1:size(tmp,2));
    plot(T, tmp, 'color', pData.colors(spineCh,:));
    set(hAxSpines, 'ytick', [])
    xlabel('time (s)'); ylabel('Z-score')
end
set([hAxSoma hAxSpines], 'box', 'off')
linkaxes([hAxSoma hAxSpines], 'x');
end

function hF = plotTrialAverages(sData, pData)
toPlot = 'dFF';
traceType = 1;

for epoch = 1:length(pData)
    %Plot activity aligned to trial start and to reward
    isSoma = strcmpi(pData(epoch).names, 'soma');
    outputCh = 2;
    D = pData(epoch).(toPlot); %data to plot
    D = D(:,:,:,traceType,1:min(end,40)); %use default trace type
    tt = (1:size(D,1)) * pData(epoch).frametime; %time vector
    output = D(:,isSoma,outputCh,1,:);


    %mean and standard error of output signal over trials
    mO = mean(output,5, 'omitnan');
    eO = std(output,0,5, 'omitmissing')./sqrt(sum(~isnan(output),5)-1);
    eO(isnan(eO)) = 0;

    hF = figure;
    hAxAvgOut(epoch) = axes;
    plot(tt, squeeze(output(:,1,1,1,:)), 'color', pData(epoch).colors(outputCh,:));
    hold on, plot(tt, mO, 'k', 'linewidth', 2);
    xlabel('time (s)');
    ylabel('dFF');

    selTime = tt>2 & tt<10; %time window for averaging dFF within trial
    normTime = tt<2;
    trialMeans{epoch} = squeeze(mean(output(selTime,1,1,1,:),1,'omitmissing'));
    controlMeans{epoch} = squeeze(mean(output(normTime,1,1,1,:),1,'omitmissing'));
end
linkaxes(hAxAvgOut);
set(hAxAvgOut, 'xlim', [0 20])
% figure,
% shadedErrorPlot(tt,mO,eO,pData.colors(outputCh,:))



% N = shiftdim(sqrt(pData.noise(:,:,pData.traceType,:)), -1);
%
% tmpD = D(:,~isSoma, inputCh,1,:); %all input
% tmpN = N(:,~isSoma, inputCh,1,:);
% mO = mean(tmpD,5, 'omitnan');
% ste = std(tmpD,0,5, 'omitmissing')./sqrt(sum(~isnan(tmpD),5)-1);
% ste(~isfinite(ste)) = 0;
% scale = mean(tmpN,5, 'omitnan');
% time = (0:size(tmpD,1)-1)*pData.frametime;
% hF = figure,
% shadedErrorPlot(time, mO./scale + (1:size(mO,2)), real(ste)./scale, pData.colors(inputCh,:))

end

function hF = plotPairwise(sData, pData)
tmp = Dnorm(:,~isSoma, inputCh,1,:);
tmp = reshape(permute(tmp, [2 1 5 4 3]), size(tmp,2), []); %tmp is now 2D [ROIs allTime]
tmp = tmp + 10*(0:(size(tmp,1)-1)); %offset for plotting
tmp(:, ~keepFrames) = []; %remove ends of trials
T = sData(1).frametime*(1:size(tmp,2));
plot(T, tmp, 'color', pData.colors(somaCh,:));
set(hAxSoma, 'xtick', [])
ylabel('Z-score')

end

function hF = plotTotalInput(sData, pData)
%make a plot with the soma activity and the sum glutamate signal (in
%photons). Compute crosscorrelations between input and output
toPlot = 'dF';
D = pData.(toPlot); %data to plot
D = D(:,:,:,pData.traceType,:); %use default trace type

%get trial lengths
keepFrames = true(1, size(D,1)*size(D,5));
for trialIx = size(D,5):-1:1
    trialLength(trialIx) = find(~all(isnan(D(:,:,1,1,trialIx)),2), 1, 'last');
    keepFrames(((trialIx-1)*size(D,1)+trialLength(trialIx)+1):(trialIx*size(D,1))) = false;
end

%sum the fluorescence signal
isSoma = strcmpi(pData.names, 'soma');

outputCh = 2;
inputCh = 1;

tmpOut = D(:,isSoma,outputCh,:,:);
%tmpOut = tmpOut - mean(tmpOut, [1 5], 'omitnan');
output = sum(tmpOut, 2, 'omitnan');%in case there are multiple soma ROIs, sum them

% %deconvolve output using OASIS
% for trialIx = 1:size(output,5)
%     df= output(:,:,:,:,trialIx);
%     [c, s, options] = deconvolveCa(df, 'foopsi','type', 'ar1','pars', exp(-1/20), 'optimize_pars', false, 'optimize_b', false);
%     %figure, plot(df); hold on, plot(c); hold on, plot(s)
%     out_deconv(:,1,1,1,trialIx) = s;
% end

tmpIn= D(:,~isSoma,inputCh,:,:);
tmpIn = tmpIn - mean(tmpIn, [1], 'omitnan');
input = sum(tmpIn, 2, 'omitnan'); % omitting nans assumed mean dF=0 where not measured

figure,
hAx(1) = subplot(2,1,1)
plot(output(:), 'color', pData.colors(outputCh,:));
hAx(2)= subplot(2,1,2)
plot(input(:), 'color', pData.colors(inputCh,:));
linkaxes(hAx, 'x')

%%%
[r_io, r_io_shuff, lags] = xcorr_vs_shuffle(squeeze(input), squeeze(output), 5/sData(1).frametime);
hF(1) = figure;
plot(lags*pData.frametime, r_io, 'color', 'b', 'linewidth', 2);
hold on, plot(lags*pData.frametime,  r_io_shuff, 'color', [0.5 0.5 0.5],'linewidth', 2);
hold on, plot([0 0],  get(gca, 'ylim'), 'k:','linewidth', 2);
xlabel('lag (s)');
ylabel('Xcorrelation input vs output')
legend({'', 'trial shuffle'})

[r_ii, r_ii_shuff, lags] = xcorr_vs_shuffle(squeeze(input), squeeze(input), 5/sData(1).frametime);
hF(2) = figure;
plot(lags*pData.frametime, r_ii, 'color', pData.colors(inputCh,:),'linewidth', 2);
hold on, plot(lags*pData.frametime,  r_ii_shuff, 'color', [0.5 0.5 0.5],'linewidth', 2);
hold on, plot([0 0],  get(gca, 'ylim'), 'k:','linewidth', 2);
xlabel('lag (s)');
ylabel('Input Autocorrelation')
legend({'', 'trial shuffle'})

[r_oo, r_oo_shuff, lags] = xcorr_vs_shuffle(squeeze(output), squeeze(output), 5/sData(1).frametime);
hF(3) = figure;
plot(lags*pData.frametime, r_oo, 'color',  pData.colors(outputCh,:), 'linewidth', 2);
hold on, plot(lags*pData.frametime,  r_oo_shuff,'color', [0.5 0.5 0.5], 'linewidth', 2);
hold on, plot([0 0],  get(gca, 'ylim'), 'k:','linewidth', 2);
xlabel('lag (s)');
ylabel('Output Autocorrelation')
legend({'', 'trial shuffle'})

end

function [r, rshuff, lags] = xcorr_vs_shuffle(d1,d2, window)
%computes cross-correlation of d1 and d2 across trials and compares to a
rii = nan(2*window+1,size(d1,2));
rij = nan(2*window+1,size(d1,2), size(d2,2));
for ix1  = 1:size(d1,2)
    [rii(:,ix1), lags] = xcorr(d1(:,ix1), d2(:,ix1), window);

    for ix2 = 1:size(d2,2)
        if ix2~=ix1
            rij(:,ix1,ix2) = xcorr(d1(:,ix1), d2(:,ix2), window);
        else
            rij(:,ix1,ix2) = nan;
        end
    end
end
r = mean(rii,2, 'omitnan');
rshuff= mean(rij, [2 3], 'omitnan');
end