function hF = plotBCIexpt(sData)
%sData is an array of structs #epochs x #DMDs in size
%each struct in sData is generated by the function spineAnalysisExpt

colors = [0.3 0.8 0.1; 0.8 0 0.3]; %ch1 yellow ch2 red
nROIs = size(sData.traces,2);
plotChannel = ones(1, nROIs);
plotChannel(strcmpi(sData.maskData.names, 'soma')) = 2; %plot soma in red



hF = figure('name', 'all trials');
for ROIix = nROIs:-1:1
    tmp = squeeze(sData.traces(:,ROIix, plotChannel(ROIix),2,:));
    tmp(tmp==0) = nan;
    tmp = (tmp-median(tmp,1, 'omitnan'))./reshape(sqrt(sData.noise(ROIix,plotChannel(ROIix),2,:)), 1,[]); %normalized trace

    numTrials = size(tmp,2);
    tAll(:, ROIix) = tmp(:);
    %tMean(:,ROIix) = mean(tmp,2, 'omitnan');

    %concatenate normalized trials
    hAx(ROIix) = subplot(nROIs, 1, ROIix);
    trialbounds = size(sData.traces,1)*(1:numTrials);
    plot(tAll(:, ROIix), 'color', colors(plotChannel(ROIix),:)); hold on;
    ylim = [min(tAll(:, ROIix), [],'all','omitnan') max(tAll(:, ROIix), [], 'all','omitnan')];
    %plot trial boundaries
    plot(reshape([trialbounds ; trialbounds ; trialbounds], 1, []), repmat([ylim nan], [1 numTrials]), 'k')
    %plot(T, nanfastsmooth(tNorm, 7, 3, 0.5), 'color', colors(cix,:), 'linewidth', 2);
    ylabel([sData.maskData.names{ROIix}]);

    %label plots
    if ROIix<nROIs
        set(hAx(ROIix), 'xticklabel', [], 'tickdir', 'out');
    else
        xlabel('time (s)');
    end
    if ~any(isnan(ylim))
        set(hAx(ROIix), 'ylim', ylim);
    end
end
set(hAx, 'box', 'off')
linkaxes(hAx, 'x');
end

function sData = computeDFF(sData)
    %for each ROI

    

end

function totalInput

    %high-pass filter at F_cut

    %discard any window of data less than 2/F_cut wide

end