function [figures, pData] = plotBCIexpt(sData)
%sData is an array of structs #epochs x #DMDs in size
%each struct in sData is generated by the function spineAnalysisExpt
%
%sData.traces is an array of size [time ROIs channels traceType trial#] aligned to
%trial start. Traces have units of (photons x 100)
%
%outputs:
%figures are the figure handles
%pData is the data used in the plots

pData.colors = [0.3 0.8 0.1; 0.8 0 0.3]; %ch1 yellow ch2 red
pData.traceType = 2; %which trace version to use; 1=raw ROIs, 2=motion subtracted ROIs,...

%merge data from the two DMDs
for epoch = 1:size(sData, 1)
    [pData.F, pData.dF, pData.F0, pData.noise, pData.dmdIxs, pData.names] = mergeDMDs(sData(epoch,:));
    
    %make plots specific for this epoch
    hF1 = plotTotalInput(sData,pData);
    hF2 = plotAllTraces(sData, pData);






end


    
end

function [F, dF, F0, noise, dmdIxs, names] = mergeDMDs(sData)
    for dmdNum = 1:length(sData)
        Tt = sData(dmdNum).traces;
        Nn = sData(dmdNum).noise;
        if dmdNum==1 %first DMD
            F = Tt;
            noise = Nn;
            dmdIxs = ones(1,size(Tt,2));
            names = sData(dmdNum).maskData.names;
        else
            if size(Tt,1)>size(F,1)
                F((size(F,1)+1):size(Tt,1),:,:,:,:) = nan;
            else
                Tt((size(Tt,1)+1):size(F,1),:,:,:,:) = nan; 
            end
            F= cat(2,F,Tt);
            noise = cat(1, noise, Nn);
            dmdIxs = cat(2, dmdIxs, dmdNum*ones(1,size(Tt,2)));
            names = cat(2, names,  sData(dmdNum).maskData.names);
        end
    end

    [F0] = computeF0(F);
    dF = F-F0;
end

function [F0out] = computeF0(F) 
%fits DFF; assumes first dimension is time
window = 200; %samples

origSz = size(F);
F  =reshape(F, size(F,1),[]);
F0out = nan(size(F));
for traceIx = 1:size(F,2)
    Ffit = F(:,traceIx);
    for iter = 1:4
        F0 = nanfastsmooth(Ffit, window, 2, 0.5);
        %dif = F-F0;
        %below = dif(dif<=0);
        %thresh = mean(below);
        Ffit = min(Ffit, F0);%-thresh);
    end
    F0out(:,traceIx) = F0;
end
F0out = reshape(F0out, origSz);
end

function hF = plotAllTraces(sData, pData)

%Figure with 2 subplots: 1 for soma, 1 for all synapses
    toPlot = 'dF';
    D = pData.(toPlot); %data to plot
    D = D(:,:,:,pData.traceType,:);
    Dnorm = D./shiftdim(sqrt(pData.noise(:,:,pData.traceType,:)), -1); %normalized to noise estimate

%get trial lengths
keepFrames = true(1, size(D,1)*size(D,5));
for trialIx = size(D,5):-1:1
    trialLength(trialIx) = find(~all(isnan(Dnorm(:,:,1,1,trialIx)),2), 1, 'last'); 
    keepFrames(((trialIx-1)*size(D,1)+trialLength(trialIx)+1):(trialIx*size(D,1))) = false;
end

hF = figure('name', 'all trials');
isSoma = strcmpi(pData.names, 'soma');
somaCh = 2; spineCh = 1;
hAxSoma = [];
if any(isSoma)
    hAxSoma = subplot(10,1,1);
    tmp = Dnorm(:,isSoma, somaCh,1,:);
    tmp = reshape(permute(tmp, [2 1 5 4 3]), size(tmp,2), []); %tmp is now 2D [ROIs allTime]
    tmp = tmp + 10*(0:(size(tmp,1)-1)); %offset for plotting
    tmp(:, ~keepFrames) = []; %remove ends of trials
    T = sData(1).frametime*(1:size(tmp,2));
    plot(T, tmp, 'color', pData.colors(somaCh,:));
    set(hAxSoma, 'xtick', [])
    ylabel('Z-score')
end
hAxSpines = subplot(10,1,2:10);
    tmp = Dnorm(:,~isSoma, spineCh,1,:);
    tmp = reshape(permute(tmp, [2 1 5 4 3]), size(tmp,2), []); %tmp is now 2D [ROIs allTime]
    tmp = tmp + 10*(0:(size(tmp,1)-1))'; %offset for plotting
    tmp(:, ~keepFrames) = []; %remove ends of trials
    T = sData(1).frametime*(1:size(tmp,2));
    plot(T, tmp, 'color', pData.colors(spineCh,:));
    set(hAxSpines, 'ytick', [])
    xlabel('time (s)'); ylabel('Z-score')

set([hAxSoma hAxSpines], 'box', 'off')
linkaxes([hAxSoma hAxSpines], 'x');
end

function hF = plotTrialAverages
    %Plot activity aligned to trial start and to reward

end

function hF = plotTotalInput(sData)
%make a plot with the soma activity and the sum glutamate signal (in
%photons). Compute crosscorrelations between input and output
toPlot = 'dF';
D = pData.(toPlot); %data to plot
D = D(:,:,:,pData.traceType,:); %use default trace type

%get trial lengths
keepFrames = true(1, size(D,1)*size(D,5));
for trialIx = size(D,5):-1:1
    trialLength(trialIx) = find(~all(isnan(D(:,:,1,1,trialIx)),2), 1, 'last'); 
    keepFrames(((trialIx-1)*size(D,1)+trialLength(trialIx)+1):(trialIx*size(D,1))) = false;
end

%sum the fluorescence signal
isSoma = strcmpi(pData.names, 'soma');

outputCh = 2;
inputCh = 1;

tmpOut = D(:,isSoma,inputCh,1,:);
tmpOut = tmpOut - mean(tmpOut, [1 5], 'omitnan');
output = sum(D(:,isSoma,outputCh,1,:), 2, 'omitnan');

tmpIn= D(:,~isSoma,inputCh,1,:);
tmpIn = tmpIn - mean(tmpIn, [1 5], 'omitnan');
input = sum(tmpIn, 2, 'omitnan'); % omitting nans assumed mean dF=0 where not measured

figure, 
subplot(2,1,1)
plot(output(:))

subplot(2,1,2)
plot(input(:))

%%%
r = xcorr(input, output, 10/sData(1).frametime)

end