function [f,g] = expoMF(x, data)
f = sum((data ...
        -x(1:size(data,1))*ones(1,size(data,2))...
        -x(size(data,1)+1:2*size(data,1))*exp(-x(3*size(data,1)+1)*(1:size(data,2)))...
        -x(2*size(data,1)+1:3*size(data,1))*exp(-x(3*size(data,1)+2)*(1:size(data,2)))).^2,'all');

if nargout > 1
    g(1:size(data,1)) = -2*sum(data...
                            -x(1:size(data,1))*ones(1,size(data,2))...
                            -x(size(data,1)+1:2*size(data,1))*exp(-x(3*size(data,1)+1)*(1:size(data,2)))...
                            -x(2*size(data,1)+1:3*size(data,1))*exp(-x(3*size(data,1)+2)*(1:size(data,2))),2);

    g(size(data,1)+1:2*size(data,1)) = -2*sum((data...
                                            -x(1:size(data,1))*ones(1,size(data,2))...
                                            -x(size(data,1)+1:2*size(data,1))*exp(-x(3*size(data,1)+1)*(1:size(data,2)))...
                                            -x(2*size(data,1)+1:3*size(data,1))*exp(-x(3*size(data,1)+2)*(1:size(data,2))))...
                                         .*repmat(exp(-x(3*size(data,1)+1)*(1:size(data,2))),[size(data,1) 1]),2);
    g(2*size(data,1)+1:3*size(data,1)) = -2*sum((data...
                                            -x(1:size(data,1))*ones(1,size(data,2))...
                                            -x(size(data,1)+1:2*size(data,1))*exp(-x(3*size(data,1)+1)*(1:size(data,2)))...
                                            -x(2*size(data,1)+1:3*size(data,1))*exp(-x(3*size(data,1)+2)*(1:size(data,2))))...
                                         .*repmat(exp(-x(3*size(data,1)+2)*(1:size(data,2))),[size(data,1) 1]),2);

    g(3*size(data,1)+1) = 2*sum(data...
                                -x(1:size(data,1))*ones(1,size(data,2))...
                                -x(size(data,1)+1:2*size(data,1))*exp(-x(3*size(data,1)+1)*(1:size(data,2)))...
                                -x(2*size(data,1)+1:3*size(data,1))*exp(-x(3*size(data,1)+2)*(1:size(data,2)))...
                           .*(x(size(data,1)+1:2*size(data,1))...
                              *((1:size(data,2)).*exp(-x(3*size(data,1)+1)*(1:size(data,2))))),'all');
    g(3*size(data,1)+2) = 2*sum(data...
                                -x(1:size(data,1))*ones(1,size(data,2))...
                                -x(size(data,1)+1:2*size(data,1))*exp(-x(3*size(data,1)+1)*(1:size(data,2)))...
                                -x(2*size(data,1)+1:3*size(data,1))*exp(-x(3*size(data,1)+2)*(1:size(data,2)))...
                           .*(x(2*size(data,1)+1:3*size(data,1))...
                              *((1:size(data,2)).*exp(-x(3*size(data,1)+2)*(1:size(data,2))))),'all');
end

end